# Generated by Django 4.0.4 on 2022-05-07 07:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('phonenumber', models.CharField(max_length=255, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('user_type', models.IntegerField(choices=[(1, 'Parents'), (2, 'Health professionals'), (3, 'Diagnosing person'), (4, 'Admin')], default=3)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AutismRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A1', models.IntegerField(choices=[(0, 'Always'), (0, 'Usually'), (1, 'Sometimes'), (1, 'Rarely'), (1, 'Never')], default=None)),
                ('A2', models.IntegerField(choices=[(0, 'Always'), (0, 'Usually'), (1, 'Sometimes'), (1, 'Rarely'), (1, 'Never')], default=None)),
                ('A3', models.IntegerField(choices=[(0, 'Always'), (0, 'Usually'), (1, 'Sometimes'), (1, 'Rarely'), (1, 'Never')], default=None)),
                ('A4', models.IntegerField(choices=[(0, 'Always'), (0, 'Usually'), (1, 'Sometimes'), (1, 'Rarely'), (1, 'Never')], default=None)),
                ('A5', models.IntegerField(choices=[(0, 'Always'), (0, 'Usually'), (1, 'Sometimes'), (1, 'Rarely'), (1, 'Never')], default=None)),
                ('A6', models.IntegerField(choices=[(0, 'Always'), (0, 'Usually'), (1, 'Sometimes'), (1, 'Rarely'), (1, 'Never')], default=None)),
                ('A7', models.IntegerField(choices=[(0, 'Always'), (0, 'Usually'), (1, 'Sometimes'), (1, 'Rarely'), (1, 'Never')], default=None)),
                ('A8', models.IntegerField(choices=[(0, 'Always'), (0, 'Usually'), (1, 'Sometimes'), (1, 'Rarely'), (1, 'Never')], default=None)),
                ('A9', models.IntegerField(choices=[(0, 'Always'), (0, 'Usually'), (1, 'Sometimes'), (1, 'Rarely'), (1, 'Never')], default=None)),
                ('A10', models.IntegerField(choices=[(1, 'Always'), (1, 'Usually'), (0, 'Sometimes'), (0, 'Rarely'), (0, 'Never')], default=None)),
                ('Age_mons', models.IntegerField()),
                ('Qchat_10_Score', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('Ethnicity', models.CharField(max_length=150)),
                ('Jaundice', models.BooleanField(default=False)),
                ('Who_completed_the_test', models.CharField(default='parent', max_length=100)),
                ('Why_are_you_taken_the_screening', models.CharField(default=None, max_length=200)),
                ('class_variable', models.BooleanField()),
                ('percentage', models.FloatField()),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
