# Generated by Django 4.0.4 on 2022-05-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_app', '0003_alter_autismrecord_jaundice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autismrecord',
            name='Family_mem_with_ASD',
            field=models.IntegerField(choices=[(1, 'Yes'), (1, 'No')], default=None),
        ),
    ]
