# Generated by Django 4.0.4 on 2022-05-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_app', '0004_autismrecord_family_mem_with_asd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autismrecord',
            name='Family_mem_with_ASD',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], default=None),
        ),
    ]
